# Generated by Django 5.2.1 on 2025-05-16 06:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('salary_range', models.JSONField(default=dict)),
                ('company_name', models.CharField(max_length=200)),
                ('posting_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('required_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('scheduled', 'Scheduled')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-posting_date'],
            },
        ),
    ]
