# Generated by Django 5.2.1 on 2025-05-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title'], name='job_job_title_23b697_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company_name'], name='job_job_company_89a64b_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='job_job_status_41049a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['posting_date'], name='job_job_posting_730cea_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['expiration_date'], name='job_job_expirat_6ca8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='job_job_locatio_3214b2_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'posting_date'], name='job_job_status_414fac_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'expiration_date'], name='job_job_status_122569_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['description'], name='description_idx'),
        ),
    ]
