name: Backend CI

on:
  pull_request:
    paths:
      - '.github/workflows/backend-ci.yml'
      - 'job-platform-demo-backend/**'
jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./job-platform-demo-backend

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.0'

    - name: Create test results directory
      run: mkdir -p app/test-results

    - name: Set directory permissions
      run: chmod -R 777 app/test-results

    - name: Start services with docker-compose
      run: |
        docker compose up -d --build

    - name: Run Tests
      run: |
        docker compose run --rm app sh -c "python manage.py wait_for_db && pytest --junitxml=test-results/junit.xml"

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./job-platform-demo-backend/app/test-results/